"""align timestamps and deployment model

Revision ID: 06b50de3d1f1
Revises: 4ab3031e855a
Create Date: 2026-01-17 11:55:46.173794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06b50de3d1f1'
down_revision: Union[str, Sequence[str], None] = '4ab3031e855a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1️⃣ Corriger les données existantes avant NOT NULL
    op.execute("UPDATE deployments SET start_time = now() WHERE start_time IS NULL")
    op.execute("UPDATE metric_samples SET timestamp = now() WHERE timestamp IS NULL")
    op.execute("UPDATE projects SET created_at = now() WHERE created_at IS NULL")
    op.execute("UPDATE projects SET updated_at = now() WHERE updated_at IS NULL")
    op.execute("UPDATE subscriptions SET created_at = now() WHERE created_at IS NULL")
    op.execute("UPDATE subscriptions SET updated_at = now() WHERE updated_at IS NULL")

    # 2️⃣ Appliquer NOT NULL et server_default
    op.alter_column('deployments', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("now()"),
               nullable=False)
    op.alter_column('metric_samples', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("now()"),
               nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("now()"),
               nullable=False)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("now()"),
               nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("now()"),
               nullable=False)
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("now()"),
               nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('metric_samples', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('deployments', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
