"""fix timestamps: use timezone-aware DateTime with func.now()

Revision ID: 0da839e7c9a3
Revises: 822fa1a3c5ec
Create Date: 2026-01-16 14:40:53.618529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da839e7c9a3'
down_revision: Union[str, Sequence[str], None] = '822fa1a3c5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
