"""Mise à jours des tables

Revision ID: 0fe6fc0b1e31
Revises: 5688e5d32246
Create Date: 2026-01-21 14:33:34.830831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fe6fc0b1e31'
down_revision: Union[str, Sequence[str], None] = '5688e5d32246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # =============================
    # DEPLOYMENT VERDICTS
    # =============================

    op.alter_column(
        'deployment_verdicts',
        'verdict',
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=30),
        existing_nullable=False
    )

    op.alter_column(
        'deployment_verdicts',
        'summary',
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        nullable=True
    )

    # ⚠️ Ne pas supprimer confidence/details maintenant
    # (garde compatibilité avec anciens verdicts)

    # =============================
    # DEPLOYMENTS
    # =============================

    op.add_column(
        'deployments',
        sa.Column(
            'state',
            sa.String(length=20),
            nullable=False,
            server_default='finished'  # SAFE DEFAULT
        )
    )

    op.add_column(
        'deployments',
        sa.Column(
            'pipeline_result',
            sa.String(length=50),
            nullable=True
        )
    )


    # Copier status → pipeline_result
    op.execute("""
        UPDATE deployments
        SET pipeline_result = status
        WHERE pipeline_result IS NULL
    """)

    # ⚠️ NE PAS drop status maintenant

    # =============================
    # METRIC SAMPLES (nouveau modèle)
    # =============================

    op.add_column(
        'metric_samples',
        sa.Column('phase', sa.String(length=10), nullable=True)
    )

    op.add_column(
        'metric_samples',
        sa.Column('requests_per_sec', sa.Float(), nullable=True)
    )

    op.add_column(
        'metric_samples',
        sa.Column('latency_p95', sa.Float(), nullable=True)
    )

    op.add_column(
        'metric_samples',
        sa.Column('error_rate', sa.Float(), nullable=True)
    )

    op.add_column(
        'metric_samples',
        sa.Column('cpu_usage', sa.Float(), nullable=True)
    )

    op.add_column(
        'metric_samples',
        sa.Column('memory_usage', sa.Float(), nullable=True)
    )

    op.add_column(
        'metric_samples',
        sa.Column(
            'collected_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        )
    )

    # ⚠️ Ne pas drop window/name/value/timestamp maintenant

    # =============================
    # PROJECTS
    # =============================

    op.add_column(
        'projects',
        sa.Column(
            'plan',
            sa.String(length=20),
            nullable=False,
            server_default='free'
        )
    )

    op.alter_column(
        'projects',
        'envs',
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'envs',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.drop_column('projects', 'plan')
    op.add_column('metric_samples', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('metric_samples', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('metric_samples', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('metric_samples', sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('metric_samples', sa.Column('window', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('metric_samples', 'collected_at')
    op.drop_column('metric_samples', 'memory_usage')
    op.drop_column('metric_samples', 'cpu_usage')
    op.drop_column('metric_samples', 'error_rate')
    op.drop_column('metric_samples', 'latency_p95')
    op.drop_column('metric_samples', 'requests_per_sec')
    op.drop_column('metric_samples', 'phase')
    op.add_column('deployments', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('deployments', 'pipeline_result')
    op.drop_column('deployments', 'state')
    op.add_column('deployment_verdicts', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('deployment_verdicts', sa.Column('details', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.alter_column('deployment_verdicts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('deployment_verdicts', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('deployment_verdicts', 'verdict',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
