"""fix timestamps: use timezone-aware DateTime with timezone

Revision ID: 105da69f353e
Revises: 0da839e7c9a3
Create Date: 2026-01-16 14:51:00.805668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105da69f353e'
down_revision: Union[str, Sequence[str], None] = '0da839e7c9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
