"""initial - TABLES and Nullable false in users and subscriptions

Revision ID: 5af4b354608e
Revises: 66b06ca6c531
Create Date: 2026-01-16 02:14:26.377317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af4b354608e'
down_revision: Union[str, Sequence[str], None] = '66b06ca6c531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(None, 'subscriptions', ['project_id'])
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.alter_column('subscriptions', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
