"""initial - TABLES

Revision ID: 66b06ca6c531
Revises: 7b51c9a9e940
Create Date: 2026-01-16 02:09:07.030032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66b06ca6c531'
down_revision: Union[str, Sequence[str], None] = '7b51c9a9e940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('envs', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_api_key'), 'projects', ['api_key'], unique=True)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('env', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('window', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscriptions', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('subscriptions', sa.Column('max_envs', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
    op.add_column('subscriptions', sa.Column('current_period_end', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('subscriptions_user_id_key'), 'subscriptions', type_='unique')
    op.create_unique_constraint(None, 'subscriptions', ['stripe_subscription_id'])
    op.drop_constraint(op.f('subscriptions_user_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscriptions', 'started_at')
    op.drop_column('subscriptions', 'user_id')
    op.drop_column('subscriptions', 'ended_at')
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.add_column('subscriptions', sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_user_id_fkey'), 'subscriptions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.create_unique_constraint(op.f('subscriptions_user_id_key'), 'subscriptions', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'current_period_end')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_column('subscriptions', 'max_envs')
    op.drop_column('subscriptions', 'project_id')
    op.drop_table('metric_samples')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_projects_api_key'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
