"""deployment_verdict

Revision ID: 719b9aca0eea
Revises: 547fe48fa128
Create Date: 2026-01-18 14:20:20.677747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719b9aca0eea'
down_revision: Union[str, Sequence[str], None] = '547fe48fa128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_verdicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('details', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployment_verdicts')
    # ### end Alembic commands ###
