"""drop colum status from deployment

Revision ID: b702eff8d17e
Revises: 174a24a2791d
Create Date: 2026-01-22 01:35:10.815963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b702eff8d17e'
down_revision: Union[str, Sequence[str], None] = '174a24a2791d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column('deployments', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_samples', sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.alter_column('metric_samples', 'memory_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('metric_samples', 'cpu_usage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('metric_samples', 'error_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('metric_samples', 'latency_p95',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('metric_samples', 'requests_per_sec',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('metric_samples', 'phase',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.add_column('deployments', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('deployments', 'pipeline_result',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('deployment_verdicts', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('deployment_verdicts', sa.Column('details', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.alter_column('deployment_verdicts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
