"""Test func.now()

Revision ID: c7fd62246f3f
Revises: a9437763c016
Create Date: 2026-01-17 11:18:52.990813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7fd62246f3f'
down_revision: Union[str, Sequence[str], None] = 'a9437763c016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Corriger les données AVANT les contraintes
    op.execute("""
        UPDATE users
        SET created_at = now()
        WHERE created_at IS NULL
    """)

    op.execute("""
        UPDATE users
        SET updated_at = now()
        WHERE updated_at IS NULL
    """)

    # Appliquer NOT NULL + DEFAULT
    op.alter_column(
        "users",
        "created_at",
        server_default=sa.text("now()"),
        nullable=False
    )

    op.alter_column(
        "users",
        "updated_at",
        server_default=sa.text("now()"),
        nullable=False
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
