"""add duration_seconds and fix deployment status

Revision ID: fae9a0fc24f8
Revises: 06b50de3d1f1
Create Date: 2026-01-17 20:19:58.969659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae9a0fc24f8'
down_revision: Union[str, Sequence[str], None] = '06b50de3d1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'duration_seconds')
    # ### end Alembic commands ###
