SLACK_TYPE_FIRST_VERDICT_AVAILABLE = "S-FIRST-VERDICT"
SLACK_TYPE_CRITICAL_VERDICT_ALERT = "S-CRITICAL-VERDICT"
SLACK_TYPE_TEST_MESSAGE = "S-TEST"

SUPPORTED_SLACK_TYPES = {
    SLACK_TYPE_FIRST_VERDICT_AVAILABLE,
    SLACK_TYPE_CRITICAL_VERDICT_ALERT,
    SLACK_TYPE_TEST_MESSAGE,
}

